### ISSUE TITLE
Can’t fetch pipelines from merge requests because of mismatched `ref`

### ISSUE THREAD

**Issue by shivjm** [mvisonneau/gitlab-ci-pipelines-exporter#280]
I’m not sure whether GitLab changed something recently, in the run up to version 14, but I have the exporter set up with a Webhook and it’s unable to fetch any pipelines. For example (with my project details edited):
```
{"ip-address":"10.244.1.187:42854","level":"debug","msg":"webhook request","time":"2021-05-31T13:46:23Z","user-agent":"GitLab/14.0.0-pre"}
{"level":"info","msg":"received a pipeline webhook from GitLab for a ref, triggering metrics pull","project-name":"my-group/my-repo","ref":"my-branch","ref-kind":"merge-request","time":"2021-05-31T13:46:23Z"}
{"level":"debug","msg":"listing project pipelines","project-name":"my-group/my-repo","ref":"my-branch","time":"2021-05-31T13:46:23Z"}
{"level":"debug","msg":"could not find any pipeline for the ref","project-name":"my-group/my-repo","ref":"my-branch","ref-kind":"merge-request","time":"2021-05-31T13:46:23Z"}
```
I did some debugging and what I found is that GitLab’s pipeline details (now?) use `ref` like this:
```
        "ref": "refs/merge-requests/55/head",
```
If you search for pipelines using the name of the branch, it returns nothing. If you use this ref, it does show up. However, it’s not possible to generate it from the Webhook request. Instead, you can take the `sha` from the Webhook request and retrieve pipelines based on that instead (by passing a `sha` parameter instead of a `ref` parameter). I confirmed manually that it works. No matter what the `ref` is, the `sha` will always match.

**Comment by mvisonneau** [comment]
hey @shivjm, thanks for raising this issue and the associated troubleshooting. I believe this is a duplicate of #259 actually but it allowed me to figure out where to look :bow: I believe 83ca5f2 should sort it out.

**Comment by shivjm** [comment]
Thank you for the speedy response! I did see #259 but it didn’t seem like the same thing. My mistake. I’m glad I helped you find the issue, at any rate.

I updated to the latest Docker image (and confirmed that the digests match), but I’m afraid I’m still seeing the same issue:
```
"ip-address":"10.244.1.187:57670","level":"debug","msg":"webhook request","time":"2021-06-01T10:48:23Z","user-agent":"GitLab/14.0.0-pre"}
{"level":"info","msg":"received a pipeline webhook from GitLab for a ref, triggering metrics pull","project-name":"my-group/my-project","ref":"my-branch","ref-kind":"merge-request","time":"2021-06-01T10:48:23Z"}
{"level":"debug","msg":"listing project pipelines","project-name":"my-group/my-project","ref":"refs/merge-requests/my-branch/head","time":"2021-06-01T10:48:23Z"}
{"level":"debug","msg":"could not find any pipeline for the ref","project-name":"my-group/my-project","ref":"my-branch","ref-kind":"merge-request","time":"2021-06-01T10:48:23Z"}
```

**Comment by mpickering** [comment]
I don't think this is fixed still. See my comment - https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/commit/83ca5f2ad5f510e04705756dbbdc9aa847c8aaa2#r51677228

**Comment by mvisonneau** [comment]
@shivjm indeed, there was further changes required, https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/commit/436f91f1dc1fa97fca01605364c9ac0c1c829467 should fix it :crossed_fingers:

**Comment by mpickering** [comment]
I still think something isn't quite right.. with the latest change I get

```
time="2021-06-03T11:39:29-04:00" level=info msg="ref not configured in the exporter, ignoring pipeline webhook" project-name=ghc/ghc ref=5882 ref-kind=merge-request
```

Before the patch I would get

```
msg="received a pipeline webhook from GitLab for a ref, triggering metrics pull" project-name=ghc/ghc ref=wip/adinapoli-issue-19923 ref-kind=merge-request
 msg="listing project pipelines" project-name=ghc/ghc ref=refs/merge-requests/wip/adinapoli-issue-19923/head
 msg="could not find any pipeline for the ref" project-name=ghc/ghc ref=wip/adinapoli-issue-19923 ref-kind=merge-request
```

**Comment by mvisonneau** [comment]
@mpickering, indeed this is following some breaking changes I am about to release as part of `v0.5.0`, you can [already read about them in the CHANGELOG](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/blob/main/CHANGELOG.md#unreleased).

basically you will now need to set the following to get it to work with merge requests refs:

```yaml
project_defaults:
  pull:
    refs:
      merge_requests:
        enabled: true
```

**Comment by mpickering** [comment]
I tried making that change. Still the same result, here is the config.

```
gitlab:
  token: <>
  url: 'https://gitlab.haskell.org'
projects:
  - name: ghc/ghc
    pull:
      refs:
        merge_requests:
          enabled: true
        regexp: .*
pull:
  environments_from_projects:
    on_init: false
    scheduled: false
  metrics:
    on_init: false
    scheduled: false
  projects_from_wildcards:
    on_init: false
    scheduled: false
  refs:
    regexp: .*
  refs_from_projects:
    on_init: false
    scheduled: false
server:
  listen_address: ':9887'
  webhook:
    enabled: true
    secret_token: <>
wildcards:
  - {}
```

**Comment by mvisonneau** [comment]
@mpickering can you give it a try with the following config?

```yaml
---
server:
  listen_address: ':9887'
  webhook:
    enabled: true
    secret_token: <>

gitlab:
  token: <>
  url: 'https://gitlab.haskell.org'

projects_defaults:
  pull:
    refs:
      branches:
        regexp: .*    
      merge_requests:
        enabled: true

pull:
  environments_from_projects:
    on_init: false
    scheduled: false
  metrics:
    on_init: false
    scheduled: false
  projects_from_wildcards:
    on_init: false
    scheduled: false
  refs_from_projects:
    on_init: false
    scheduled: false

wildcards: [{}]
```

**Comment by mpickering** [comment]
Still seems broken on all MRs for me. There are now no errors in the log but no metrics are populating the DB.

```
INFO[2021-06-03T17:43:16-04:00] configured                                    gitlab-endpoint="https://gitlab.haskell.org" gitlab-rate-limit=1rps
INFO[2021-06-03T17:43:16-04:00] pull projects from wildcards                  on-init=no scheduled=no
INFO[2021-06-03T17:43:16-04:00] pull environments from projects               on-init=no scheduled=no
INFO[2021-06-03T17:43:16-04:00] pull refs from projects                       on-init=no scheduled=no
INFO[2021-06-03T17:43:16-04:00] pull metrics                                  on-init=no scheduled=no
INFO[2021-06-03T17:43:16-04:00] garbage collect projects                      on-init=no scheduled="every 14400s"
INFO[2021-06-03T17:43:16-04:00] garbage collect environments                  on-init=no scheduled="every 14400s"
INFO[2021-06-03T17:43:16-04:00] garbage collect refs                          on-init=no scheduled="every 1800s"
INFO[2021-06-03T17:43:16-04:00] garbage collect metrics                       on-init=no scheduled="every 300s"
DEBU[2021-06-03T17:43:16-04:00] task scheduled                                interval_seconds=14400 task=GarbageCollectProjects
DEBU[2021-06-03T17:43:16-04:00] task scheduled                                interval_seconds=14400 task=GarbageCollectEnvironments
DEBU[2021-06-03T17:43:16-04:00] task scheduled                                interval_seconds=1800 task=GarbageCollectRefs
DEBU[2021-06-03T17:43:16-04:00] task scheduled                                interval_seconds=300 task=GarbageCollectMetrics
INFO[2021-06-03T17:43:16-04:00] http server started                           listen-address=":9887" metrics-endpoint-enabled=true openmetrics-encoding-enabled=false pprof-endpoint-enabled=false webhook-endpoint-enabled=true
DEBU[2021-06-03T17:43:27-04:00] webhook request                               ip-address="127.0.0.1:55480" user-agent=GitLab/13.12.2-ee
DEBU[2021-06-03T17:43:53-04:00] webhook request                               ip-address="127.0.0.1:55488" user-agent=GitLab/13.12.2-ee
INFO[2021-06-03T17:48:16-04:00] starting 'metrics' garbage collection        
INFO[2021-06-03T17:48:16-04:00] ending 'metrics' garbage collection          
INFO[2021-06-03T17:53:16-04:00] starting 'metrics' garbage collection        
INFO[2021-06-03T17:53:16-04:00] ending 'metrics' garbage collection          
INFO[2021-06-03T17:58:16-04:00] starting 'metrics' garbage collection        
INFO[2021-06-03T17:58:16-04:00] ending 'metrics' garbage collection          
INFO[2021-06-03T18:03:16-04:00] starting 'metrics' garbage collection        
INFO[2021-06-03T18:03:16-04:00] ending 'metrics' garbage collection          
DEBU[2021-06-03T18:06:44-04:00] webhook request                               ip-address="127.0.0.1:57544" user-agent=GitLab/13.12.2-ee
DEBU[2021-06-03T18:06:45-04:00] webhook request                               ip-address="127.0.0.1:57548" user-agent=GitLab/13.12.2-ee
INFO[2021-06-03T18:08:16-04:00] starting 'metrics' garbage collection        
INFO[2021-06-03T18:08:16-04:00] ending 'metrics' garbage collection   
```

**Comment by mvisonneau** [comment]
```
INFO[2021-06-03T23:44:05+01:00] configured                                    gitlab-endpoint="https://git.example.com" gitlab-rate-limit=25rps
INFO[2021-06-03T23:44:05+01:00] pull projects from wildcards                  on-init=no scheduled=no
INFO[2021-06-03T23:44:05+01:00] pull environments from projects               on-init=no scheduled=no
INFO[2021-06-03T23:44:05+01:00] pull refs from projects                       on-init=no scheduled=no
INFO[2021-06-03T23:44:05+01:00] pull metrics                                  on-init=no scheduled=no
INFO[2021-06-03T23:44:05+01:00] garbage collect projects                      on-init=no scheduled="every 14400s"
INFO[2021-06-03T23:44:05+01:00] garbage collect environments                  on-init=no scheduled="every 14400s"
INFO[2021-06-03T23:44:05+01:00] garbage collect refs                          on-init=no scheduled="every 1800s"
INFO[2021-06-03T23:44:05+01:00] garbage collect metrics                       on-init=no scheduled="every 300s"
DEBU[2021-06-03T23:44:05+01:00] task scheduled                                interval_seconds=14400 task=GarbageCollectProjects
DEBU[2021-06-03T23:44:05+01:00] task scheduled                                interval_seconds=14400 task=GarbageCollectEnvironments
DEBU[2021-06-03T23:44:05+01:00] task scheduled                                interval_seconds=1800 task=GarbageCollectRefs
DEBU[2021-06-03T23:44:05+01:00] task scheduled                                interval_seconds=300 task=GarbageCollectMetrics
INFO[2021-06-03T23:44:05+01:00] http server started                           listen-address=":5000" metrics-endpoint-enabled=true openmetrics-encoding-enabled=false pprof-endpoint-enabled=false webhook-endpoint-enabled=true
DEBU[2021-06-03T23:44:14+01:00] webhook request                               ip-address="127.0.0.1:40074" user-agent=GitLab/13.12.1-ee
INFO[2021-06-03T23:44:14+01:00] project ref not currently exported but its configuration matches a wildcard, triggering a pull of the projects from this wildcard  project-name=foo/bar ref=1234 ref-kind=merge-request
INFO[2021-06-03T23:44:14+01:00] done looking up for wildcards matching the project ref  project-name=foo/bar ref=1234 ref-kind=merge-request
DEBU[2021-06-03T23:44:14+01:00] listing all projects from wildcard            wildcard-archived=false wildcard-owner-include-subgroups=false wildcard-owner-kind= wildcard-owner-name= wildcard-search=
[..]
```

hmm interesting, I cannot manage to reproduce  :thinking: I added some further logging details in 366cd92 if you feel like trying it out.

**Comment by mpickering** [comment]
```
DEBU[2021-06-04T03:36:31-04:00] webhook request                               ip-address="127.0.0.1:59408" user-agent=GitLab/13.12.2-ee
DEBU[2021-06-04T03:36:31-04:00] project ref not matching wildcard, skipping..  project-name=ghc/ghc ref=5897 ref-kind=merge-request
INFO[2021-06-04T03:36:31-04:00] done looking up for wildcards matching the project ref  project-name=ghc/ghc ref=5897 ref-kind=merge-request
```

**Comment by mvisonneau** [comment]
and you confirm the wildcard is a global one (`wildcards: [{}]`)?

**Comment by mpickering** [comment]
The issue was the config you gave me had `projects_defaults` rather than `project_defaults`. Would it be possible to add some validation to the config to catch errors like this?

**Comment by mvisonneau** [comment]
ah right! my bad :facepalm: yep that would be great :+1:

**Comment by davidtlascelles** [comment]
I'm still seeing this issue on 0.5.2-39-g287e04c

Here's a log from a webhook request:
```
time="2022-01-31T14:59:12Z" level=debug msg="webhook request" ip-address="127.0.0.1:49140" user-agent=GitLab/14.6.1-ee
time="2022-01-31T14:59:12Z" level=info msg="received a pipeline webhook from GitLab for a ref, triggering metrics pull" project-name=path/to/project ref=3467 ref-kind=merge-request
time="2022-01-31T14:59:12Z" level=trace msg="listing project pipelines" page=1 project-name=path/to/projec ref=refs/merge-requests/3467/head
time="2022-01-31T14:59:12Z" level=debug msg="could not find any pipeline for the ref" project-name=path/to/projec ref=3467 ref-kind=merge-request
```

Here's my config.yml:
```
log:
  level: trace
server:
  listen_address: ':8080'
  webhook:
    enabled: true
    secret_token: <>
gitlab:
  url: http://gitlab:80
  token: <>
  health_url: http://gitlab:80/-/health
pull:
  environments_from_projects:
    on_init: false
    scheduled: false
  metrics:
    on_init: false
    scheduled: false
  projects_from_wildcards:
    on_init: false
    scheduled: false
  refs_from_projects:
    on_init: false
    scheduled: false
project_defaults:
  output_sparse_status_metrics: false
  pull:
    refs:
      branches:
        regexp: ".*"
        max_age_seconds: 1209600
        exclude_deleted: false
      tags:
        enabled: false
      merge_requests:
        enabled: true
        max_age_seconds: 1209600
    pipeline:
      jobs:
        enabled: true
      variables:
        enabled: true
projects:
  - name: path/to/project
wildcards: [{}]
```

Any progress on this bug?

**Comment by shivjm** [comment]
I’ve got my stack up and running again. Sorry for leaving this in a state of limbo for so long. Unfortunately, though @davidtlascelles’s detailed comments are extremely helpful, I had to move away from the webhook approach for unrelated reasons, and as such am unable to test either the current version or the proposed solution!

**Comment by stewarca** [comment]
Did anybody ever get this to work?

I've set it up to use Webhooks but it doesn't seem to be able to get any of the Merge Requests, I'm seeing these:

Apr 22 15:02:00 maastricht start-pipeline-monitor.sh: time="2025-04-22T15:02:00-07:00" level=debug msg="webhook request" ip-address="10.102.25.55:57834" user-agent=GitLab/17.10.4-ee
Apr 22 15:02:00 maastricht start-pipeline-monitor.sh: time="2025-04-22T15:02:00-07:00" level=info msg="received a pipeline webhook from GitLab for a ref, triggering metrics pull" project-name=Calibre/Calibre ref=6463 ref-kind=merge-request
Apr 22 15:02:00 maastricht start-pipeline-monitor.sh: time="2025-04-22T15:02:00-07:00" level=debug msg="**could not find any pipeline for the ref**" project-name=Calibre/Calibre ref=6463 ref-kind=merge-request

Apr 22 15:02:01 maastricht start-pipeline-monitor.sh: time="2025-04-22T15:02:01-07:00" level=debug msg="webhook request" ip-address="10.102.25.55:57850" user-agent=GitLab/17.10.4-ee
Apr 22 15:02:01 maastricht start-pipeline-monitor.sh: time="2025-04-22T15:02:01-07:00" level=info msg="**deleted ref from the store**" project-name=Calibre/Calibre reason="received merge request merge event from webhook" ref=6463 ref-kind=merge-request

My Configuration looks like this:
log:
  level: debug
gitlab:
  url: https://calgit.wv.mentorg.com
  # The GitLab token is set through the$GCPE_GITLAB_TOKEN environment variable
  token: ************************************************
  #maximum_requests_per_second: 2
  #burstable_requests_per_second: 5
  maximum_jobs_queue_size: 10000 # Default 1000 - last resort to up this
server:
  webhook:
    enabled: true               # default false
    secret_token: **********************************************
pull:
  projects_from_wildcards:
    on_init: false
    scheduled: false
    interval_seconds: 31500      # 1800 default
  environments_from_projects:
    on_init: false
    scheduled: false
    interval_seconds: 31500      # 300 default
  refs_from_projects:
    on_init: false              # default true
    scheduled: false
    interval_seconds: 900       # 300 default
  metrics:
    on_init: false               # default true
    scheduled: false
    interval_seconds: 60        # 30 secs default
garbage_collect:
  projects_from_wildcards:
    on_init: false              # default false
    scheduled: false            # default true
    interval_seconds: 14400     # 14000 default
  environments:
    on_init: false              # default false
    scheduled: false            # default true
    interval_seconds: 14400     # 14000 default
  refs:
    on_init: false              # default false
    scheduled: false            # default true
    interval_seconds: 1800      # 1800 default
  metrics:
    on_init: false              # default false
    scheduled: false            # default true
    interval_seconds: 600       # 30 secs default
project_defaults:
# Whether to output sparse job and pipeline status metrics.
#   # When enabled, only the status label matching the last run
#     # of a pipeline or job will be submitted (optional, default: true)
  #output_sparse_status_metrics: true
  output_sparse_status_metrics: false
  pull:
    refs:
      merge_requests:
        enabled: true
projects:
  - name: NextLevel/Level1
    pull:
      refs:
        branches:
          enabled: true
          regexp: "^(?:trunk|20[0-9]{4}\\.[1-4])$"
          max_age_seconds: 604800  # 1 week
        tags:
          # Do not look for release branch tags pipelines, they're not working
          regexp: "^(?:cb|nightly)_.*$"
          max_age_seconds: 604800  # 1 week
          enabled: true
        merge_requests:
          enabled: true
      pipeline:
        jobs:
          enabled: false
wildcards: [{}]

**Comment by stewarca** [comment]
Did anybody ever get this to work?

I've set it up to use Webhooks but it doesn't seem to be able to get any of the Merge Requests, I'm seeing these:

Apr 22 15:02:00 maastricht start-pipeline-monitor.sh: time="2025-04-22T15:02:00-07:00" level=debug msg="webhook request" ip-address="10.102.25.55:57834" user-agent=GitLab/17.10.4-ee
Apr 22 15:02:00 maastricht start-pipeline-monitor.sh: time="2025-04-22T15:02:00-07:00" level=info msg="received a pipeline webhook from GitLab for a ref, triggering metrics pull" project-name=MyProject/MyProject ref=6463 ref-kind=merge-request
Apr 22 15:02:00 maastricht start-pipeline-monitor.sh: time="2025-04-22T15:02:00-07:00" level=debug msg="could not find any pipeline for the ref" project-name=MyProject/MyProject ref=6463 ref-kind=merge-request

Apr 22 15:02:01 maastricht start-pipeline-monitor.sh: time="2025-04-22T15:02:01-07:00" level=debug msg="webhook request" ip-address="10.102.25.55:57850" user-agent=GitLab/17.10.4-ee
Apr 22 15:02:01 maastricht start-pipeline-monitor.sh: time="2025-04-22T15:02:01-07:00" level=info msg="deleted ref from the store" project-name=MyProject/MyProject reason="received merge request merge event from webhook" ref=6463 ref-kind=merge-request

Here's my Config file:

[config.txt](https://github.com/user-attachments/files/19857839/config.txt)

Any help is appreciated.

**Comment by strowi** [comment]
This has been bugging me for a while, I finally gave it a show altoghough not a go-pro ->  [PR](https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/pull/1081) which seems to fi the issue for me.
